In [1]:
#importar as bibliotecas 
from numpy import pi
from numpy import sys
from numpy import newaxis
import numpy as np

In [2]:
print('Versão atual do numpy',np.__version__)

Versão atual do numpy 1.18.5


In [4]:
rg = np.random.default_rng(1)
a = np.floor(10*rg.random((2,2)))
a

array([[5., 9.],
       [1., 9.]])

In [5]:
b = np.floor(10*rg.random((2,2)))
b

array([[3., 4.],
       [8., 4.]])

In [6]:
#Empilha a matriz a e b de forma vertical
np.vstack((a, b))

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.]])

In [7]:
#Empilha a matriz a e b de forma horizontal
np.hstack((a, b))

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [8]:
np.column_stack((a, b))

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [9]:
c = np.array([4.,2.])
d = np.array([3.,8.])

In [10]:
c

array([4., 2.])

In [11]:
d

array([3., 8.])

In [12]:
np.hstack((c, d))

array([4., 2., 3., 8.])

In [13]:
np.vstack((c, d))

array([[4., 2.],
       [3., 8.]])

In [16]:
c[: , newaxis]

array([[4.],
       [2.]])

In [18]:
np.column_stack((c[:, newaxis], d[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [19]:
np.hstack((c[:, newaxis], d[:, newaxis]))

array([[4., 3.],
       [2., 8.]])